/* <lm-chillerpiping-viewer> — reference-locked procedural piping corridor. */
(function(){
'use strict';
const ESM='https://cdn.jsdelivr.net/npm/three@0.160.0';
const SEC={
 PB:{name:'BLUE-ARROW PIPE PAIR',type:'Chilled-water pipework',devices:'Two insulated mains · blue direction plates'},
 PR:{name:'RED-ARROW PIPE PAIR',type:'Chilled-water pipework',devices:'Two insulated mains · red direction plates'},
 SP:{name:'SUPPORTS & HANGERS',type:'Supports',devices:'Channels · rods · pipe clamps'},
 CT:{name:'CABLE TRAYS',type:'Containment',devices:'Side trays · centre tray · repeated rungs'},
 LT:{name:'CORRIDOR LIGHTING',type:'Lighting',devices:'Linear housings · luminous diffusers'},
 AR:{name:'CORRIDOR ARCHITECTURE',type:'Architecture',devices:'Walls · piers · ceiling void · floor'},
 DR:{name:'CORRIDOR DOORS',type:'Architecture',devices:'Left and right doors · frames · handles'}
};
const IDS=Object.keys(SEC);
const MAP=[[/^CP_PipeBlue_/,'PB'],[/^CP_PipeRed_/,'PR'],[/^CP_Supports_/,'SP'],[/^CP_CableTray_/,'CT'],[/^CP_Lighting_/,'LT'],[/^CP_Architecture_/,'AR'],[/^CP_Door/,'DR']];
const secOfNode=o=>{for(let n=o;n;n=n.parent)for(const [re,id] of MAP)if(re.test(n.name||''))return id;return null;};
const HUDCFG={views:[],walls:true,colour:true,explode:false,poster:'',loadingLabel:'Building chiller-piping corridor',hint:'Reference view · Drag for a small look-around · Scroll zoom<br>R reset · W walls · C colour · Esc deselect'};
class LMChillerPipingViewer extends HTMLElement{
 connectedCallback(){if(this._built)return;this._built=true;const sh=this.attachShadow({mode:'open'});sh.innerHTML=LMHUD.markup(HUDCFG);this._sections={};this._sel=null;this._hover=null;this._reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;this.setAttribute('tabindex','0');this.setAttribute('role','application');this.setAttribute('aria-label','Reference-locked BIM viewer of a chiller-piping service corridor.');
  this._hud=LMHUD.attach(this,sh,HUDCFG,{sections:this._sections,order:IDS,SEC,onReset:()=>{this._select?.(null);this._goReference?.();},onSelect:id=>this._select?.(id),onHover:id=>this._applyHover?.(id),onVisibility:fn=>this._applyVis?.(fn),onWalls:off=>this._applyWalls?.(off),onColour:on=>this._applyColour?.(on)});
  this.addEventListener('keydown',this._onKey);const start=()=>{if(this._started)return;this._started=true;import(ESM+'/+esm').then(T=>this._init(T)).catch(e=>this._fallback(e));};setTimeout(start,40);this._observer=new IntersectionObserver(es=>es.forEach(e=>{this._onScreen=e.isIntersecting;if(e.isIntersecting){start();this._resume();}}),{rootMargin:'240px'});this._observer.observe(this);
 }
 disconnectedCallback(){this._observer?.disconnect();if(this._raf)cancelAnimationFrame(this._raf);this._dispose?.();}
 _fallback(e){console.error('Chiller piping viewer:',e);this._hud?.fail();}
 _resume(){if(this._tick&&!this._raf)this._tick();}
 _sync(){if(!this._hud)return;this._hud.sel=this._sel;this._hud.hover=this._hover;this._hud.sync();}
 _panel(id){this._hud?.setProps(id);this._hud?.setTip(id?SEC[id].name:'');}
 _onKey=e=>{const k=e.key;if(k==='Escape'||k==='0')this._select?.(null);else if(this._lookKey?.(k)){}else if(this._hud?.key(k)){}else return;e.preventDefault();};
  _init(THREE){const cv=this.shadowRoot.querySelector('canvas'),renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.outputColorSpace=THREE.SRGBColorSpace;
   const scene=new THREE.Scene();scene.background=new THREE.Color(0x303943);scene.fog=new THREE.Fog(0x343d46,22,43);const camera=new THREE.PerspectiveCamera(58,1,.05,80);
   scene.add(new THREE.HemisphereLight(0xf0f4f5,0x596067,1.75));const key=new THREE.DirectionalLight(0xf4f6f5,1.9);key.position.set(-3,8,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-8;key.shadow.camera.right=8;key.shadow.camera.top=7;key.shadow.camera.bottom=-4;key.shadow.camera.far=45;scene.add(key,key.target);key.target.position.set(0,2.8,-10);
   for(let z=2;z>-19;z-=5.1){const l=new THREE.PointLight(0xfff2d8,1.65,8,2);l.position.set(0,3.0,z);scene.add(l);}
  const root=LMChillerPipingModel.create(THREE),sections=this._sections,pick=[],walls=[],catMat={};let dirty=true;root.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;const id=secOfNode(o);if(!id)return;(sections[id]=sections[id]||{meshes:[]}).meshes.push(o);o.userData.sec=id;pick.push(o);if(id==='AR'||id==='DR')walls.push(o);});scene.add(root);
  IDS.forEach(id=>{const s=sections[id];if(!s)return;const bb=new THREE.Box3();s.meshes.forEach(o=>bb.expandByObject(o));s.box=bb;s.centre=bb.getCenter(new THREE.Vector3());});
  this.dataset.sculptReady=String(!!root.userData.sculptRuntime);this.dataset.sculptComponents=String(root.userData.sculptRuntime?.components?.length||0);
  this._applyVis=fn=>{IDS.forEach(id=>sections[id]?.meshes.forEach(o=>o.visible=fn(id)));dirty=true;};this._applyWalls=off=>{walls.forEach(o=>o.visible=!off);dirty=true;};this._applyColour=on=>{IDS.forEach(id=>{const s=sections[id];if(!s)return;if(!catMat[id])catMat[id]=new THREE.MeshStandardMaterial({color:this._hud.colourOf(id),roughness:.58,metalness:.12});s.meshes.forEach(o=>{if(!o.userData.m0)o.userData.m0=o.material;o.material=on?catMat[id]:o.userData.m0;});});dirty=true;};
  const REFERENCE={target:new THREE.Vector3(0,3.62,-7.1),radius:10.35,theta:0,phi:1.781};const YAW_LIMIT=THREE.MathUtils.degToRad(3),PITCH_LIMIT=THREE.MathUtils.degToRad(2),R_MIN=3.3,R_MAX=REFERENCE.radius,HFOV_TAN=Math.tan(THREE.MathUtils.degToRad(70)/2);let target=REFERENCE.target.clone(),radius=REFERENCE.radius,theta=REFERENCE.theta,phi=REFERENCE.phi;
  const clamp=()=>{theta=THREE.MathUtils.clamp(theta,REFERENCE.theta-YAW_LIMIT,REFERENCE.theta+YAW_LIMIT);phi=THREE.MathUtils.clamp(phi,REFERENCE.phi-PITCH_LIMIT,REFERENCE.phi+PITCH_LIMIT);radius=THREE.MathUtils.clamp(radius,R_MIN,R_MAX);};const publish=()=>{this.dataset.cameraMode='reference-locked-corridor';this.dataset.cameraRadius=radius.toFixed(4);this.dataset.cameraMaxRadius=R_MAX.toFixed(4);this.dataset.cameraYawDeg=THREE.MathUtils.radToDeg(theta-REFERENCE.theta).toFixed(3);this.dataset.cameraPitchDeg=THREE.MathUtils.radToDeg(phi-REFERENCE.phi).toFixed(3);};
  this._goReference=()=>{target.copy(REFERENCE.target);radius=REFERENCE.radius;theta=REFERENCE.theta;phi=REFERENCE.phi;dirty=true;};this._lookKey=k=>{if(k==='ArrowLeft'||k==='ArrowRight'){theta+=THREE.MathUtils.degToRad(k==='ArrowLeft'?-.5:.5);clamp();dirty=true;return true;}if(k==='ArrowUp'||k==='+'||k==='='){radius*=.9;clamp();dirty=true;return true;}if(k==='ArrowDown'||k==='-'||k==='_'){radius*=1.1;clamp();dirty=true;return true;}return false;};
  let dragging=false,lastX=0,lastY=0,moved=false;cv.style.touchAction='none';cv.addEventListener('pointerdown',e=>{dragging=true;moved=false;lastX=e.clientX;lastY=e.clientY;cv.setPointerCapture(e.pointerId);this._downAt=Date.now();});cv.addEventListener('pointerup',e=>{dragging=false;if(cv.hasPointerCapture(e.pointerId))cv.releasePointerCapture(e.pointerId);});cv.addEventListener('pointermove',e=>{if(dragging){const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;if(Math.abs(dx)+Math.abs(dy)>1)moved=true;theta-=dx*.0015;phi+=dy*.0012;clamp();dirty=true;return;}const r=cv.getBoundingClientRect();this._mx=(e.clientX-r.left)/r.width*2-1;this._my=-(e.clientY-r.top)/r.height*2+1;this._hoverDirty=true;});cv.addEventListener('wheel',e=>{e.preventDefault();radius*=1+e.deltaY*.0012;clamp();dirty=true;},{passive:false});
  const ray=new THREE.Raycaster(),mv=new THREE.Vector2(),tint=(id,n)=>{const s=sections[id],done=new Set();s?.meshes.forEach(o=>{const m=o.material;if(!m.emissive||done.has(m.uuid))return;done.add(m.uuid);if(m.userData.e0===undefined){m.userData.e0=m.emissive.getHex();m.userData.ei0=m.emissiveIntensity;}if(n){m.emissive.setHex(0x00b0f0);m.emissiveIntensity=n;}else{m.emissive.setHex(m.userData.e0);m.emissiveIntensity=m.userData.ei0;}});dirty=true;};this._applyHover=id=>{if(this._hover===id)return;if(this._hover&&this._hover!==this._sel)tint(this._hover,0);this._hover=id;if(id&&id!==this._sel)tint(id,.16);cv.style.cursor=id?'pointer':'default';if(!this._sel)this._panel(id);this._sync();};this._select=id=>{if(this._sel)tint(this._sel,0);this._sel=id;if(id){tint(id,.3);this._panel(id);}else this._panel(this._hover);this._sync();};cv.addEventListener('click',()=>{if(moved||Date.now()-(this._downAt||0)>260)return;this._select(this._hover&&this._sel!==this._hover?this._hover:null);});
  const resize=()=>{const w=this.clientWidth||900,h=this.clientHeight||600;renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=THREE.MathUtils.clamp(THREE.MathUtils.radToDeg(2*Math.atan(HFOV_TAN/Math.max(camera.aspect,.01))),38,88);camera.updateProjectionMatrix();dirty=true;};const ro=new ResizeObserver(resize);ro.observe(this);resize();this._dispose=()=>{ro.disconnect();scene.traverse(o=>{o.geometry?.dispose();const ms=o.material?(Array.isArray(o.material)?o.material:[o.material]):[];ms.forEach(m=>{Object.values(m).forEach(v=>v?.isTexture&&v.dispose());m.dispose();});});renderer.dispose();};
  this.debugScene={scene,camera,renderer,root,reference:REFERENCE,render:()=>renderer.render(scene,camera)};const tick=()=>{this._raf=requestAnimationFrame(tick);if(this._onScreen===false||document.hidden){cancelAnimationFrame(this._raf);this._raf=null;return;}if(this._hoverDirty&&!dragging){this._hoverDirty=false;mv.set(this._mx,this._my);ray.setFromCamera(mv,camera);const hit=ray.intersectObjects(pick,false)[0];this._applyHover(hit?hit.object.userData.sec:null);}if(dirty){dirty=false;camera.position.set(target.x+radius*Math.sin(phi)*Math.sin(theta),target.y+radius*Math.cos(phi),target.z+radius*Math.sin(phi)*Math.cos(theta));camera.lookAt(target);renderer.render(scene,camera);publish();}};this._tick=tick;this._loaded=true;this._sync();this._hud.ready();tick();
 }
}
if(!customElements.get('lm-chillerpiping-viewer'))customElements.define('lm-chillerpiping-viewer',LMChillerPipingViewer);
})();
